language: php

env:
  - PIMPLE_EXT=no
  - PIMPLE_EXT=yes

before_script:
  - if [ "$PIMPLE_EXT" == "yes" ]; then sh -c "cd ext/pimple && phpize && ./configure && make && sudo make install"; fi
  - if [ "$PIMPLE_EXT" == "yes" ]; then echo "extension=pimple.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`; fi

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

script:
  - if [ "$PIMPLE_EXT" == "yes" ]; then sh -c "cd ext/pimple && yes n | make test"; fi
  - phpunit

matrix:
  exclude:
    - php: hhvm
      env: PIMPLE_EXT=yes
